/*
Navicat MySQL Data Transfer

Source Server         : 实时行情数据主库
Source Server Version : 50524
Source Host           : 10.4.32.92:3306
Source Database       : bhfxquote

Target Server Type    : MYSQL
Target Server Version : 50524
File Encoding         : 65001

Date: 2015-02-11 16:17:22
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `ax_config`
-- ----------------------------
DROP TABLE IF EXISTS `ax_config`;
CREATE TABLE `ax_config` (
  `id` int(5) NOT NULL AUTO_INCREMENT,
  `symbol` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `cnbc_symbol` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT 'cnbc的代号',
  `status` enum('active','inactive') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'active',
  `title` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `subTitle` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
  `enTitle` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `type` enum('forex','commodity','indice','stock','etf','bond','cfdindice','cfdcommodity','cfdbond','cfdstock','cfdforex') COLLATE utf8_unicode_ci NOT NULL,
  `url` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `numberFormat` varchar(10) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0.00',
  `show_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '展示页面',
  `price_source` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '实时价格来源',
  `open_close_source` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '开收盘价格来源',
  `diff_url` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '用于参照价格的链接',
  `open_time` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '开收盘时间',
  `spider_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `diff_allow` float NOT NULL,
  `importance` int(11) NOT NULL DEFAULT '0' COMMENT '重要性',
  `remark` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '备注说明',
  `diff_price` float NOT NULL DEFAULT '0' COMMENT '参照网站的价格',
  `site_price` float NOT NULL DEFAULT '0' COMMENT 'wallstreetcn上面的价格',
  `ctime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '对比时间',
  `site_ctime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '主站价格最新的时间',
  `diff_status` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '0代表数据是对的，1代表数据是错的',
  PRIMARY KEY (`id`),
  UNIQUE KEY `symbol` (`symbol`)
) ENGINE=InnoDB AUTO_INCREMENT=240 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of ax_config
-- ----------------------------
INSERT INTO `ax_config` VALUES ('1', 'XAUUSD', '', 'active', '黄金', '黄金', 'Gold', 'commodity', 'xauusd', '0.00', 'http://markets.wallstreetcn.com/commodity/xauusd', 'MT4', 'http://www.investing.com/commodities/gold', 'http://www.investing.com/commodities/gold', '', 'investing_open_close.py', '0.01', '5', '', '1236.1', '1236.02', '1423642639', '1423642628', '0');
INSERT INTO `ax_config` VALUES ('2', 'XAGUSD', '', 'active', '白银', '白银', 'Silver', 'commodity', 'xagusd', '0.00', 'http://markets.wallstreetcn.com/commodity/xagusd', 'MT4', 'http://www.investing.com/commodities/silver', 'http://www.investing.com/commodities/silver', '', 'investing_open_close.py', '0.01', '3', '', '16.983', '16.984', '1423642645', '1423642628', '0');
INSERT INTO `ax_config` VALUES ('3', 'Copper', '', 'active', '铜', '铜', 'Copper', 'commodity', 'copper', '0.000', 'http://markets.wallstreetcn.com/commodity/copper', 'MT4', 'http://www.investing.com/commodities/copper', 'http://www.investing.com/commodities/copper', '', 'investing_open_close.py', '0.01', '3', '', '2.55', '2.549', '1423642646', '1423642609', '0');
INSERT INTO `ax_config` VALUES ('4', 'UKOil', '', 'active', '布伦特石油', '布油', 'Brent Oil', 'commodity', 'ukoil', '0.00', 'http://markets.wallstreetcn.com/commodity/ukoil', 'MT4', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=LCOCV1&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=LCOCV1&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', '', 'cnbc_open_close.py', '0.01', '5', '', '56.59', '56.6', '1423642640', '1423642635', '0');
INSERT INTO `ax_config` VALUES ('5', 'USOil', '', 'active', 'WTI石油', 'WTI石油', 'USOil', 'commodity', 'usoil', '0.00', 'http://markets.wallstreetcn.com/commodity/usoil', 'MT4', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=%40CL.1&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=%40CL.1&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', '', 'cnbc_open_close.py', '0.01', '5', '', '50.26', '50.26', '1423642640', '1423642634', '0');
INSERT INTO `ax_config` VALUES ('6', 'NGAS', '', 'active', '天然气', '天然气', 'Natural Gas', 'commodity', 'ngas', '0.000', 'http://markets.wallstreetcn.com/commodity/ngas', 'MT4', 'http://www.investing.com/commodities/natural-gas', 'http://www.investing.com/commodities/natural-gas', '', 'investing_open_close.py', '0.01', '3', '', '2.724', '2.719', '1423642647', '1423642605', '0');
INSERT INTO `ax_config` VALUES ('7', 'XPDUSD', '', 'active', '钯金', '钯金', 'XPD/USD', 'commodity', 'xpdusd', '0.00', 'http://markets.wallstreetcn.com/commodity/xpdusd', 'MT4', 'http://www.investing.com/commodities/palladium', 'http://www.investing.com/commodities/palladium', '', 'investing_open_close.py', '0.01', '3', '', '769.8', '768.5', '1423642649', '1423642476', '0');
INSERT INTO `ax_config` VALUES ('8', 'XPTUSD', '', 'active', '铂金', '铂金', 'Platinum', 'commodity', 'xptusd', '0.00', 'http://markets.wallstreetcn.com/commodity/xptusd', 'MT4', 'http://www.investing.com/commodities/platinum', 'http://www.investing.com/commodities/platinum', '', 'investing_open_close.py', '0.01', '3', '', '1210.2', '1207.5', '1423642650', '1423642618', '0');
INSERT INTO `ax_config` VALUES ('9', 'USDOLLAR', '', 'inactive', '美元指数', '美元指数', 'USDOLLAR', 'commodity', 'usdollar', '0', 'http://markets.wallstreetcn.com/commodity/usdollar', '', '', '', '', '', '0', '0', '美元指数属于外汇类，此条目禁用', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('10', 'EURUSD', '', 'active', '欧元/美元', '欧元美元', 'EUR/USD', 'forex', 'eurusd', '0.0000', 'http://markets.wallstreetcn.com/forex/eurusd', 'MT4', '', 'http://www.investing.com/currencies/eur-usd', '', 'investing_open_close.py', '0.001', '5', '', '1.1315', '1.1314', '1423642641', '1423642638', '0');
INSERT INTO `ax_config` VALUES ('11', 'GBPUSD', '', 'active', '英镑/美元', '英镑/美元', 'GBP/USD', 'forex', 'gbpusd', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpusd', 'MT4', '', 'http://www.investing.com/currencies/gbp-usd', '', 'investing_open_close.py', '0.001', '3', '', '1.5261', '1.5261', '1423642558', '1423642557', '0');
INSERT INTO `ax_config` VALUES ('12', 'USDJPY', '', 'active', '美元/日元', '美元日元', 'USD/JPY', 'forex', 'usdjpy', '0.00', 'http://markets.wallstreetcn.com/forex/usdjpy', 'MT4', '', 'http://www.investing.com/currencies/usd-jpy', '', 'investing_open_close.py', '0.002', '5', '', '119.79', '119.777', '1423642643', '1423642641', '0');
INSERT INTO `ax_config` VALUES ('13', 'USDCHF', '', 'active', '美元/瑞郎', '美元/瑞郎', 'USD/CHF', 'forex', 'usdchf', '0.0000', 'http://markets.wallstreetcn.com/forex/usdchf', 'MT4', '', 'http://www.investing.com/currencies/usd-chf', '', 'investing_open_close.py', '0.001', '3', '', '0.9281', '0.9277', '1423642560', '1423642556', '0');
INSERT INTO `ax_config` VALUES ('14', 'AUDUSD', '', 'active', '澳元/美元', '澳元/美元', 'AUD/USD', 'forex', 'audusd', '0.0000', 'http://markets.wallstreetcn.com/forex/audusd', 'MT4', '', 'http://www.investing.com/currencies/aud-usd', '', 'investing_open_close.py', '0.001', '3', '', '0.7754', '0.7753', '1423642561', '1423642559', '0');
INSERT INTO `ax_config` VALUES ('15', 'USDCAD', '', 'active', '美元/加元', '美元/加元', 'USD/CAD', 'forex', 'usdcad', '0.0000', 'http://markets.wallstreetcn.com/forex/usdcad', 'MT4', '', 'http://www.investing.com/currencies/usd-cad', '', 'investing_open_close.py', '0.001', '3', '', '1.2596', '1.2595', '1423642563', '1423642563', '0');
INSERT INTO `ax_config` VALUES ('16', 'EURGBP', '', 'active', '欧元/英镑', '欧元/英镑', 'EUR/GBP', 'forex', 'eurgbp', '0.0000', 'http://markets.wallstreetcn.com/forex/eurgbp', 'MT4', '', 'http://www.investing.com/currencies/eur-gbp', '', 'investing_open_close.py', '0.001', '3', '', '0.7412', '0.7412', '1423642565', '1423642564', '0');
INSERT INTO `ax_config` VALUES ('17', 'USDHKD', '', 'active', '美元/港币', '美元/港币', 'USD/HKD', 'forex', 'usdhkd', '0.0000', 'http://markets.wallstreetcn.com/forex/usdhkd', 'MT4', '', 'http://www.investing.com/currencies/usd-hkd', '', 'investing_open_close.py', '0.001', '3', '', '7.7541', '7.7538', '1423642566', '1423642563', '0');
INSERT INTO `ax_config` VALUES ('18', 'USDZAR', '', 'active', '美元/南非兰特', '美元/南非兰特', 'USD/ZAR', 'forex', 'usdzar', '0.0000', 'http://markets.wallstreetcn.com/forex/usdzar', 'MT4', '', 'http://www.investing.com/currencies/usd-zar', '', 'investing_open_close.py', '0.001', '3', '', '11.7662', '11.7644', '1423642567', '1423642565', '0');
INSERT INTO `ax_config` VALUES ('19', 'USDSEK', '', 'active', '美元/瑞典克朗', '美元/瑞典克朗', 'USD/SEK', 'forex', 'usdsek', '0.0000', 'http://markets.wallstreetcn.com/forex/usdsek', 'MT4', '', 'http://www.investing.com/currencies/usd-sek', '', 'investing_open_close.py', '0.001', '3', '', '8.3407', '8.3397', '1423642569', '1423642568', '0');
INSERT INTO `ax_config` VALUES ('20', 'USDDKK', '', 'active', '美元/丹麦克朗', '美元/丹麦克朗', 'USD/DKK', 'forex', 'usddkk', '0.0000', 'http://markets.wallstreetcn.com/forex/usddkk', 'MT4', '', 'http://www.investing.com/currencies/usd-dkk', '', 'investing_open_close.py', '0.001', '3', '', '6.5798', '6.5792', '1423642570', '1423642569', '0');
INSERT INTO `ax_config` VALUES ('21', 'USDSGD', '', 'active', '美元/新加坡元', '美元/新加坡元', 'USD/SGD', 'forex', 'usdsgd', '0.0000', 'http://markets.wallstreetcn.com/forex/usdsgd', 'MT4', '', 'http://www.investing.com/currencies/usd-sgd', '', 'investing_open_close.py', '0.001', '3', '', '1.3581', '1.3578', '1423642571', '1423642569', '0');
INSERT INTO `ax_config` VALUES ('22', 'USDNOK', '', 'active', '美元/挪威克朗', '美元/挪威克朗', 'USD/NOK', 'forex', 'usdnok', '0.0000', 'http://markets.wallstreetcn.com/forex/usdnok', 'MT4', '', 'http://www.investing.com/currencies/usd-nok', '', 'investing_open_close.py', '0.001', '3', '', '7.5862', '7.5848', '1423642572', '1423642571', '0');
INSERT INTO `ax_config` VALUES ('23', 'USDTRY', '', 'active', '美元/土耳其里拉', '美元/土耳其里拉', 'USD/TRY', 'forex', 'usdtry', '0.0000', 'http://markets.wallstreetcn.com/forex/usdtry', 'MT4', '', 'http://www.investing.com/currencies/usd-try', '', 'investing_open_close.py', '0.001', '3', '', '2.4948', '2.4945', '1423642574', '1423642570', '0');
INSERT INTO `ax_config` VALUES ('24', 'USDMXN', '', 'active', '美元/墨西哥比索', '美元/墨西哥比索', 'USD/MXN', 'forex', 'usdmxn', '0.0000', 'http://markets.wallstreetcn.com/forex/usdmxn', 'MT4', '', 'http://www.investing.com/currencies/usd-mxn', '', 'investing_open_close.py', '0.001', '3', '', '14.9664', '14.9626', '1423642575', '1423642573', '0');
INSERT INTO `ax_config` VALUES ('25', 'USDPLN', '', 'active', '美元/波兰兹罗提', '美元/波兰兹罗提', 'USD/PLN', 'forex', 'usdpln', '0.0000', 'http://markets.wallstreetcn.com/forex/usdpln', 'MT4', '', 'http://www.investing.com/currencies/usd-pln', '', 'investing_open_close.py', '0.001', '3', '', '3.7179', '3.7169', '1423642576', '1423642567', '0');
INSERT INTO `ax_config` VALUES ('26', 'USDHUF', '', 'active', '美元/匈牙利福林', '美元/匈牙利福林', 'USD/HUF', 'forex', 'usdhuf', '0.0000', 'http://markets.wallstreetcn.com/forex/usdhuf', 'MT4', '', 'http://www.investing.com/currencies/usd-huf', '', 'investing_open_close.py', '0.001', '3', '', '273.47', '273.373', '1423642578', '1423642568', '0');
INSERT INTO `ax_config` VALUES ('27', 'USDRUB', '', 'active', '美元/俄罗斯卢布', '美元/俄罗斯卢布', 'USD/RUB', 'forex', 'usdrub', '0.0000', 'http://markets.wallstreetcn.com/forex/usdrub', 'MT4', '', 'http://www.investing.com/currencies/usd-rub', '', 'investing_open_close.py', '0.001', '3', '', '66.363', '66.363', '1423642579', '1423642564', '0');
INSERT INTO `ax_config` VALUES ('28', 'USDCZK', '', 'active', '美元/捷克克朗', '美元/捷克克朗', 'USD/CZK', 'forex', 'usdczk', '0.0000', 'http://markets.wallstreetcn.com/forex/usdczk', 'MT4', '', 'http://www.investing.com/currencies/usd-czk', '', 'investing_open_close.py', '0.001', '3', '', '24.4847', '24.477', '1423642580', '1423642573', '0');
INSERT INTO `ax_config` VALUES ('29', 'NZDUSD', '', 'active', '新西兰元/美元', '新西兰元/美元', 'NZD/USD', 'forex', 'nzdusd', '0.0000', 'http://markets.wallstreetcn.com/forex/nzdusd', 'MT4', '', 'http://www.investing.com/currencies/nzd-usd', '', 'investing_open_close.py', '0.001', '3', '', '0.7409', '0.7408', '1423642582', '1423642577', '0');
INSERT INTO `ax_config` VALUES ('30', 'EURJPY', '', 'active', '欧元/日元', '欧元/日元', 'EUR/JPY', 'forex', 'eurjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/eurjpy', 'MT4', '', 'http://www.investing.com/currencies/eur-jpy', '', 'investing_open_close.py', '0.002', '3', '', '135.5', '135.494', '1423642583', '1423642583', '0');
INSERT INTO `ax_config` VALUES ('31', 'EURCAD', '', 'active', '欧元/加元', '欧元/加元', 'EUR/CAD', 'forex', 'eurcad', '0.0000', 'http://markets.wallstreetcn.com/forex/eurcad', 'MT4', '', 'http://www.investing.com/currencies/eur-cad', '', 'investing_open_close.py', '0.001', '3', '', '1.4252', '1.425', '1423642585', '1423642584', '0');
INSERT INTO `ax_config` VALUES ('32', 'EURAUD', '', 'active', '欧元/澳元', '欧元/澳元', 'EUR/AUD', 'forex', 'euraud', '0.0000', 'http://markets.wallstreetcn.com/forex/euraud', 'MT4', '', 'http://www.investing.com/currencies/eur-aud', '', 'investing_open_close.py', '0.001', '3', '', '1.4591', '1.4589', '1423642586', '1423642585', '0');
INSERT INTO `ax_config` VALUES ('33', 'EURCHF', '', 'active', '欧元/瑞郎', '欧元/瑞郎', 'EUR/CHF', 'forex', 'eurchf', '0.0000', 'http://markets.wallstreetcn.com/forex/eurchf', 'MT4', '', 'http://www.investing.com/currencies/eur-chf', '', 'investing_open_close.py', '0.001', '3', '', '1.0498', '1.0497', '1423642587', '1423642574', '0');
INSERT INTO `ax_config` VALUES ('34', 'EURNZD', '', 'active', '欧元/新西兰元', '欧元/新西兰元', 'EUR/NZD', 'forex', 'eurnzd', '0.0000', 'http://markets.wallstreetcn.com/forex/eurnzd', 'MT4', '', 'http://www.investing.com/currencies/eur-nzd', '', 'investing_open_close.py', '0.001', '3', '', '1.5271', '1.5269', '1423642589', '1423642586', '0');
INSERT INTO `ax_config` VALUES ('35', 'EURSEK', '', 'active', '欧元/瑞典克朗', '欧元/瑞典克朗', 'EUR/SEK', 'forex', 'eursek', '0.0000', 'http://markets.wallstreetcn.com/forex/eursek', 'MT4', '', 'http://www.investing.com/currencies/eur-sek', '', 'investing_open_close.py', '0.001', '3', '', '9.4363', '9.4355', '1423642590', '1423642589', '0');
INSERT INTO `ax_config` VALUES ('36', 'EURNOK', '', 'active', '欧元/挪威克朗', '欧元/挪威克朗', 'EUR/NOK', 'forex', 'eurnok', '0.0000', 'http://markets.wallstreetcn.com/forex/eurnok', 'MT4', '', 'http://www.investing.com/currencies/eur-nok', '', 'investing_open_close.py', '0.001', '3', '', '8.58', '8.5786', '1423642591', '1423642590', '0');
INSERT INTO `ax_config` VALUES ('37', 'EURDKK', '', 'active', '欧元/丹麦克朗', '欧元/丹麦克朗', 'EUR/DKK', 'forex', 'eurdkk', '0.0000', 'http://markets.wallstreetcn.com/forex/eurdkk', 'MT4', '', 'http://www.investing.com/currencies/eur-dkk', '', 'investing_open_close.py', '0.001', '3', '', '7.4442', '7.4438', '1423642592', '1423641818', '0');
INSERT INTO `ax_config` VALUES ('38', 'EURTRY', '', 'active', '欧元/土耳其里拉', '欧元/土耳其里拉', 'EUR/TRY', 'forex', 'eurtry', '0.0000', 'http://markets.wallstreetcn.com/forex/eurtry', 'MT4', '', 'http://www.investing.com/currencies/eur-try', '', 'investing_open_close.py', '0.001', '3', '', '2.8234', '2.8228', '1423642594', '1423642593', '0');
INSERT INTO `ax_config` VALUES ('39', 'EURPLN', '', 'active', '欧元/波兰兹罗提', '欧元/波兰兹罗提', 'EUR/PLN', 'forex', 'eurpln', '0.0000', 'http://markets.wallstreetcn.com/forex/eurpln', 'MT4', '', 'http://www.investing.com/currencies/eur-pln', '', 'investing_open_close.py', '0.001', '3', '', '4.2063', '4.2059', '1423642595', '1423642591', '0');
INSERT INTO `ax_config` VALUES ('40', 'EURHUF', '', 'active', '欧元/匈牙利福林', '欧元/匈牙利福林', 'EUR/HUF', 'forex', 'eurhuf', '0.0000', 'http://markets.wallstreetcn.com/forex/eurhuf', 'MT4', '', 'http://www.investing.com/currencies/eur-huf', '', 'investing_open_close.py', '0.001', '3', '', '309.375', '309.3', '1423642596', '1423642593', '0');
INSERT INTO `ax_config` VALUES ('41', 'EURCZK', '', 'active', '欧元/捷克克朗', '欧元/捷克克朗', 'EUR/CZK', 'forex', 'eurczk', '0.0000', 'http://markets.wallstreetcn.com/forex/eurczk', 'MT4', '', 'http://www.investing.com/currencies/eur-czk', '', 'investing_open_close.py', '0.001', '3', '', '27.7001', '27.697', '1423642598', '1423642575', '0');
INSERT INTO `ax_config` VALUES ('42', 'GBPJPY', '', 'active', '英镑/日元', '英镑/日元', 'GBP/JPY', 'forex', 'gbpjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpjpy', 'MT4', '', 'http://www.investing.com/currencies/gbp-jpy', '', 'investing_open_close.py', '0.002', '3', '', '182.81', '182.804', '1423642599', '1423642598', '0');
INSERT INTO `ax_config` VALUES ('43', 'AUDJPY', '', 'active', '澳元/日元', '澳元/日元', 'AUD/JPY', 'forex', 'audjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/audjpy', 'MT4', '', 'http://www.investing.com/currencies/aud-jpy', '', 'investing_open_close.py', '0.002', '3', '', '92.88', '92.855', '1423642601', '1423642597', '0');
INSERT INTO `ax_config` VALUES ('44', 'HKDJPY', '', 'active', '港元/日元', '港元/日元', 'HKD/JPY', 'forex', 'hkdjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/hkdjpy', 'MT4', '', 'http://www.investing.com/currencies/hkd-jpy', '', 'investing_open_close.py', '0.002', '3', '', '15.445', '15.436', '1423642602', '1423642600', '0');
INSERT INTO `ax_config` VALUES ('45', 'CADJPY', '', 'active', '加元/日元', '加元/日元', 'CAD/JPY', 'forex', 'cadjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/cadjpy', 'MT4', '', 'http://www.investing.com/currencies/cad-jpy', '', 'investing_open_close.py', '0.002', '3', '', '95.08', '95.061', '1423642603', '1423642602', '0');
INSERT INTO `ax_config` VALUES ('46', 'SGDJPY', '', 'active', '新加坡元/日元', '新加坡元/日元', 'SGD/JPY', 'forex', 'sgdjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/sgdjpy', 'MT4', '', 'http://www.investing.com/currencies/sgd-jpy', '', 'investing_open_close.py', '0.002', '3', '', '88.2', '88.182', '1423642604', '1423642602', '0');
INSERT INTO `ax_config` VALUES ('47', 'NZDJPY', '', 'active', '新西兰元/日元', '新西兰元/日元', 'NZD/JPY', 'forex', 'nzdjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/nzdjpy', 'MT4', '', 'http://www.investing.com/currencies/nzd-jpy', '', 'investing_open_close.py', '0.002', '3', '', '88.74', '88.719', '1423642605', '1423642602', '0');
INSERT INTO `ax_config` VALUES ('48', 'ZARJPY', '', 'active', '南非兰特/日元', '南非兰特/日元', 'ZAR/JPY', 'forex', 'zarjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/zarjpy', 'MT4', '', 'http://www.investing.com/currencies/zar-jpy', '', 'investing_open_close.py', '0.002', '3', '', '10.18', '10.163', '1423642606', '1423642605', '0');
INSERT INTO `ax_config` VALUES ('49', 'TRYJPY', '', 'active', '土耳其里拉/日元', '土耳其里拉/日元', 'TRY/JPY', 'forex', 'tryjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/tryjpy', 'MT4', '', 'http://www.investing.com/currencies/try-jpy', '', 'investing_open_close.py', '0.002', '3', '', '47.99', '47.958', '1423642607', '1423642600', '0');
INSERT INTO `ax_config` VALUES ('50', 'SEKJPY', '', 'active', '瑞典克朗兑日元', '瑞典克朗兑日元', 'SEK/JPY', 'forex', 'sekjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/sekjpy', 'MT4', '', 'http://www.investing.com/currencies/sek-jpy', '', 'investing_open_close.py', '0.002', '3', '', '14.365', '14.343', '1423642608', '1423642606', '0');
INSERT INTO `ax_config` VALUES ('51', 'NOKJPY', '', 'active', '挪威克朗/日元', '挪威克朗/日元', 'NOK/JPY', 'forex', 'nokjpy', '0.0000', 'http://markets.wallstreetcn.com/forex/nokjpy', 'MT4', '', 'http://www.investing.com/currencies/nok-jpy', '', 'investing_open_close.py', '0.002', '3', '', '15.795', '15.773', '1423642610', '1423642609', '0');
INSERT INTO `ax_config` VALUES ('52', 'GBPAUD', '', 'active', '英镑/澳元', '英镑/澳元', 'GBP/AUD', 'forex', 'gbpaud', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpaud', 'MT4', '', 'http://www.investing.com/currencies/gbp-aud', '', 'investing_open_close.py', '0.001', '3', '', '1.9686', '1.9685', '1423642611', '1423642607', '0');
INSERT INTO `ax_config` VALUES ('53', 'GBPCAD', '', 'active', '英镑/加元', '英镑/加元', 'GBP/CAD', 'forex', 'gbpcad', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpcad', 'MT4', '', 'http://www.investing.com/currencies/gbp-cad', '', 'investing_open_close.py', '0.001', '3', '', '1.923', '1.9228', '1423642613', '1423642609', '0');
INSERT INTO `ax_config` VALUES ('54', 'GBPNZD', '', 'active', '英镑/新西兰元', '英镑/新西兰元', 'GBP/NZD', 'forex', 'gbpnzd', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpnzd', 'MT4', '', 'http://www.investing.com/currencies/gbp-nzd', '', 'investing_open_close.py', '0.001', '3', '', '2.0604', '2.0602', '1423642614', '1423642613', '0');
INSERT INTO `ax_config` VALUES ('55', 'GBPCHF', '', 'active', '英镑/瑞郎', '英镑/瑞郎', 'GBP/CHF', 'forex', 'gbpchf', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpchf', 'MT4', '', 'http://www.investing.com/currencies/gbp-chf', '', 'investing_open_close.py', '0.001', '3', '', '1.416', '1.4156', '1423642616', '1423642615', '0');
INSERT INTO `ax_config` VALUES ('56', 'GBPSEK', '', 'active', '英镑/瑞典克朗', '英镑/瑞典克朗', 'GBP/SEK', 'forex', 'gbpsek', '0.0000', 'http://markets.wallstreetcn.com/forex/gbpsek', 'MT4', '', 'http://www.investing.com/currencies/gbp-sek', '', 'investing_open_close.py', '0.001', '3', '', '12.7287', '12.7257', '1423642617', '1423642614', '0');
INSERT INTO `ax_config` VALUES ('57', 'AUDCAD', '', 'active', '澳元/加元', '澳元/加元', 'AUD/CAD', 'forex', 'audcad', '0.0000', 'http://markets.wallstreetcn.com/forex/audcad', 'MT4', '', 'http://www.investing.com/currencies/aud-cad', '', 'investing_open_close.py', '0.001', '3', '', '0.9768', '0.9767', '1423642618', '1423642618', '0');
INSERT INTO `ax_config` VALUES ('58', 'CADCHF', '', 'active', '加元/瑞郎', '加元/瑞郎', 'CAD/CHF', 'forex', 'cadchf', '0.0000', 'http://markets.wallstreetcn.com/forex/cadchf', 'MT4', '', 'http://www.investing.com/currencies/cad-chf', '', 'investing_open_close.py', '0.001', '3', '', '0.7363', '0.736', '1423642619', '1423642619', '0');
INSERT INTO `ax_config` VALUES ('59', 'AUDCHF', '', 'active', '澳元/瑞郎', '澳元/瑞郎', 'AUD/CHF', 'forex', 'audchf', '0.0000', 'http://markets.wallstreetcn.com/forex/audchf', 'MT4', '', 'http://www.investing.com/currencies/aud-chf', '', 'investing_open_close.py', '0.001', '3', '', '0.7192', '0.719', '1423642621', '1423642619', '0');
INSERT INTO `ax_config` VALUES ('60', 'CHFNOK', '', 'active', '瑞郎/挪威克朗', '瑞郎/挪威克朗', 'CHF/NOK', 'forex', 'chfnok', '0.0000', 'http://markets.wallstreetcn.com/forex/chfnok', 'MT4', '', 'http://www.investing.com/currencies/chf-nok', '', 'investing_open_close.py', '0.001', '3', '', '8.174', '8.17', '1423642622', '1423642619', '0');
INSERT INTO `ax_config` VALUES ('61', 'CHFSEK', '', 'active', '瑞郎/瑞典克朗', '瑞郎/瑞典克朗', 'CHF/SEK', 'forex', 'chfsek', '0.0000', 'http://markets.wallstreetcn.com/forex/chfsek', 'MT4', '', 'http://www.investing.com/currencies/chf-sek', '', 'investing_open_close.py', '0.001', '3', '', '8.9901', '8.9873', '1423642624', '1423642617', '0');
INSERT INTO `ax_config` VALUES ('62', 'NZDCAD', '', 'active', '新西兰元/加元', '新西兰元/加元', 'NZD/CAD', 'forex', 'nzdcad', '0.0000', 'http://markets.wallstreetcn.com/forex/nzdcad', 'MT4', '', 'http://www.investing.com/currencies/nzd-cad', '', 'investing_open_close.py', '0.001', '3', '', '0.9332', '0.933', '1423642627', '1423642623', '0');
INSERT INTO `ax_config` VALUES ('63', 'AUDNZD', '', 'active', '澳元/新西兰元', '澳元/新西兰元', 'AUD/NZD', 'forex', 'audnzd', '0.0000', 'http://markets.wallstreetcn.com/forex/audnzd', 'MT4', '', 'http://www.investing.com/currencies/aud-nzd', '', 'investing_open_close.py', '0.001', '3', '', '1.0466', '1.0466', '1423642628', '1423642622', '0');
INSERT INTO `ax_config` VALUES ('64', 'CORN', '', 'active', '玉米', '玉米', 'CORN', 'commodity', 'corn', '0.00', 'http://markets.wallstreetcn.com/commodity/corn', 'MT4', 'http://www.investing.com/commodities/us-corn', '', '北京时间（夏令时）22:30-03:00场内，06:00-03:00电子', 'investing_open_close.py', '0', '0', 'MT4与investing单位不一致，investing的需要除以100', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('65', 'SOYBEAN', '', 'active', '大豆', '大豆', 'SOYBEAN', 'commodity', 'soybean', '0.0000', 'http://markets.wallstreetcn.com/commodity/soybean', 'MT4', 'http://www.investing.com/commodities/us-soybeans', '', '', 'investing_open_close.py', '0', '0', 'MT4与investing单位不一致，investing的需要除以100', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('66', 'WHEAT', '', 'active', '小麦', '小麦', 'WHEAT', 'commodity', 'wheat', '0.0000', 'http://markets.wallstreetcn.com/commodity/wheat', 'MT4', 'http://www.investing.com/commodities/us-wheat', '', '', 'investing_open_close.py', '0', '0', 'MT4与investing单位不一致，investing的需要除以100', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('67', 'SUGAR', '', 'active', '糖', '糖', 'SUGAR', 'commodity', 'sugar', '0.0000', 'http://markets.wallstreetcn.com/commodity/sugar', 'MT4', 'http://www.investing.com/commodities/us-sugar-no11', '', '', 'investing_open_close.py', '0', '0', 'MT4与investing单位不一致，investing的需要除以100', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('68', 'SPX500', '', 'active', '标普500', '标普500', 'S&P 500 Futures', 'cfdindice', 'spx500', '0.00', 'http://markets.wallstreetcn.com/cfdindice/spx500', 'MT4', 'http://www.investing.com/indices/us-spx-500', 'http://www.investing.com/indices/us-spx-500', '', 'investing_open_close.py', '0.01', '3', '', '2068.59', '2064.9', '1423642629', '1423642629', '0');
INSERT INTO `ax_config` VALUES ('69', 'NAS100', '', 'active', '纳斯达克100(cfd)', '纳斯达克100（CFD）', 'NQ 100 Futures', 'cfdindice', 'nas100', '0.00', 'http://markets.wallstreetcn.com/cfdindice/nas100', 'MT4', '', 'http://www.investing.com/indices/nq-100?cid=23660', '', '', '0.01', '3', '', '4281.15', '4279', '1423642630', '1423642628', '0');
INSERT INTO `ax_config` VALUES ('70', 'US30', '', 'active', '道琼斯指数', '道琼斯指数（CFD）', 'US 30', 'cfdindice', 'us30', '0.00', 'http://markets.wallstreetcn.com/cfdindice/us30', 'MT4', '', 'http://www.investing.com/indices/us-30-futures', '', '', '0.01', '3', '', '17789.5', '17823', '1423642632', '1423642630', '0');
INSERT INTO `ax_config` VALUES ('71', 'JPN225', '', 'active', '日经225', '日经225指数（CFD）', 'Japan 225', 'cfdindice', 'jpn225', '0.00', 'http://markets.wallstreetcn.com/cfdindice/jpn225', 'MT4', '', 'http://www.investing.com/indices/japan-225-futures', '', '', '0.01', '3', '', '17842.5', '17849', '1423642633', '1423642631', '0');
INSERT INTO `ax_config` VALUES ('72', 'HKG33', '', 'active', '恒生指数', '恒生指数(CFD)', 'Hang Sen 40', 'cfdindice', 'hkg33', '0.00', 'http://markets.wallstreetcn.com/cfdindice/hkg33', 'MT4', '', 'http://www.investing.com/indices/hong-kong-40-futures', '', '', '0.01', '3', '', '24315', '24307', '1423642634', '1423642499', '0');
INSERT INTO `ax_config` VALUES ('73', 'UK100', '', 'active', '英国100', '英国股指（CFD）', 'UK100', 'cfdindice', 'uk100', '0.00', 'http://markets.wallstreetcn.com/cfdindice/uk100', 'MT4', '', 'http://www.investing.com/indices/uk-100', '', '', '0.01', '3', '', '6823.3', '6822', '1423642635', '1423642631', '0');
INSERT INTO `ax_config` VALUES ('74', 'GER30', '', 'active', '德国30', '德国股指（CFD）', 'GER30', 'cfdindice', 'ger30', '0.00', 'http://markets.wallstreetcn.com/cfdindice/ger30', 'MT4', '', 'http://www.investing.com/indices/germany-30', '', '', '0.01', '3', '', '10782', '10780', '1423642637', '1423642632', '0');
INSERT INTO `ax_config` VALUES ('75', 'FRA40', '', 'active', '法国40', '法国股指（CFD）', 'FRA40', 'cfdindice', 'fra40', '0.00', 'http://markets.wallstreetcn.com/cfdindice/fra40', 'MT4', '', 'http://www.investing.com/indices/france-40', '', '', '0.01', '3', '', '4687.5', '4687', '1423642639', '1423642638', '0');
INSERT INTO `ax_config` VALUES ('76', 'ITA40', '', 'active', '意大利40', '意大利股指（CFD）', 'ITA40', 'cfdindice', 'ita40', '0.00', 'http://markets.wallstreetcn.com/cfdindice/ita40', 'MT4', '', 'http://www.investing.com/indices/it-mib-40', '', '', '0.01', '3', '', '20746', '20730', '1423642640', '1423642640', '0');
INSERT INTO `ax_config` VALUES ('77', 'ESP35', '', 'active', '西班牙35', '西班牙股指（CFD）', 'ESP35', 'cfdindice', 'esp35', '0.00', 'http://markets.wallstreetcn.com/cfdindice/esp35', 'MT4', '', 'http://www.investing.com/indices/spain-35', '', '', '0.01', '3', '', '10494.5', '10484', '1423642641', '1423642639', '0');
INSERT INTO `ax_config` VALUES ('78', 'EUSTX50', '', 'active', '欧洲50', '欧洲股指（CFD）', 'EUSTX50', 'cfdindice', 'eustx50', '0.00', 'http://markets.wallstreetcn.com/cfdindice/eustx50', 'MT4', '', 'http://www.investing.com/indices/eu-stoxx50', '', '', '0.01', '3', '', '3384.5', '3384', '1423642643', '1423642638', '0');
INSERT INTO `ax_config` VALUES ('79', 'AUS200', '', 'active', '澳洲200', '澳大利亚股指（CFD）', 'AUS200', 'cfdindice', 'aus200', '0.00', 'http://markets.wallstreetcn.com/cfdindice/aus200', 'MT4', '', 'http://www.investing.com/indices/aus-200?cid=53094', '', '', '0.01', '3', '', '5769.1', '5784', '1423642644', '1423642480', '0');
INSERT INTO `ax_config` VALUES ('80', 'SUI30', '', 'active', '瑞士30', '瑞士股指（CFD）', 'SUI30', 'cfdindice', 'sui30', '0.00', 'http://markets.wallstreetcn.com/cfdindice/sui30', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('81', 'SWE30', '', 'inactive', 'SWE30', 'SWE30', 'SWE30', 'forex', 'swe30', '0.00', 'http://markets.wallstreetcn.com/forex/swe30', 'MT4', '', '', '', '', '0', '0', '已停止更新', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('82', 'USDollarIndex', '', 'active', '美元指数', '美元指数', 'US Dollar Index', 'forex', 'usdollarindex', '0.00', 'http://markets.wallstreetcn.com/forex/usdollarindex', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=.DXY&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=.DXY&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', '', '北京时间 周一6:00-次日5点,周二起8:00-次日5:00(欧美冬令时需顺延一小时)', 'investing_forex.py', '0', '0', 'investing的美元指数是不对的', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('83', 'US1Month', 'US1M', 'active', '美国1月期国债', '美国1月期国债', 'U.S. 1-Month', 'bond', 'us1month', '0.000', 'http://markets.wallstreetcn.com/bond/us1month', 'http://www.investing.com/rates-bonds/u.s.-1-month-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-1-month-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('84', 'US3Month', 'US3M', 'active', '美国3月期国债', '美国3月期国债', 'U.S. 3-Month', 'bond', 'us3month', '0.000', 'http://markets.wallstreetcn.com/bond/us3month', 'http://www.investing.com/rates-bonds/u.s.-3-month-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-3-month-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('85', 'US6Month', 'US6M', 'active', '美国6月期国债', '美国6月期国债', 'U.S. 6-Month', 'bond', 'us6month', '0.000', 'http://markets.wallstreetcn.com/bond/us6month', 'http://www.investing.com/rates-bonds/u.s.-6-month-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-6-month-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('86', 'US1Year', 'US1Y', 'active', '美国1年期国债', '美国1年期国债', 'U.S. 1-Year', 'bond', 'us1year', '0.000', 'http://markets.wallstreetcn.com/bond/us1year', 'http://www.investing.com/rates-bonds/u.s.-1-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-1-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('87', 'US2Year', 'US2Y', 'active', '美国2年期国债', '美国2年期国债', 'U.S. 2-Year', 'bond', 'us2year', '0.000', 'http://markets.wallstreetcn.com/bond/us2year', 'http://www.investing.com/rates-bonds/u.s.-2-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-2-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('88', 'US3Year', 'US3Y', 'active', '美国3年期国债', '美国3年期国债', 'U.S. 3-Year', 'bond', 'us3year', '0.000', 'http://markets.wallstreetcn.com/bond/us3year', 'http://www.investing.com/rates-bonds/u.s.-3-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-3-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('89', 'US5Year', 'US5Y', 'active', '美国5年期国债', '美国5年期国债', 'U.S. 5-Year', 'bond', 'us5year', '0.000', 'http://markets.wallstreetcn.com/bond/us5year', 'http://www.investing.com/rates-bonds/u.s.-5-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-5-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('90', 'US7Year', 'US7Y', 'active', '美国7年期国债', '美国7年期国债', 'U.S. 7-Year', 'bond', 'us7year', '0.000', 'http://markets.wallstreetcn.com/bond/us7year', 'http://www.investing.com/rates-bonds/u.s.-7-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-7-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('91', 'US30Year', 'US30Y', 'active', '美国30年期国债', '美国30年期国债', 'U.S. 30-Year', 'bond', 'us30year', '0.000', 'http://markets.wallstreetcn.com/bond/us30year', 'http://www.investing.com/rates-bonds/u.s.-30-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-30-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('92', 'UK10Year', 'GB10Y-GB', 'active', '英国10年期国债', '英国10年期国债', 'UK 10-Year', 'bond', 'uk10year', '0.000', 'http://markets.wallstreetcn.com/bond/uk10year', 'http://www.investing.com/rates-bonds/uk-10-year-bond-yield', 'http://www.investing.com/rates-bonds/uk-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('93', 'Japan10Year', 'JP10Y-JP', 'active', '日本10年期国债', '日本10年期国债', 'Japan 10-Year', 'bond', 'japan10year', '0.000', 'http://markets.wallstreetcn.com/bond/japan10year', 'http://www.investing.com/rates-bonds/japan-10-year-bond-yield', 'http://www.investing.com/rates-bonds/japan-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('94', 'France10Year', 'FR10Y-FR', 'active', '法国10年期国债', '法国10年期国债', 'France 10-Year', 'bond', 'france10year', '0.000', 'http://markets.wallstreetcn.com/bond/france10year', 'http://www.investing.com/rates-bonds/france-10-year-bond-yield', 'http://www.investing.com/rates-bonds/france-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('95', 'Germany10Year', 'DE10Y-DE', 'active', '德国10年期国债', '德国10年期国债', 'Germany 10-Year', 'bond', 'germany10year', '0.000', 'http://markets.wallstreetcn.com/bond/germany10year', 'http://www.investing.com/rates-bonds/germany-10-year-bond-yield', 'http://www.investing.com/rates-bonds/germany-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('96', 'Canada10Year', 'CA10Y-CA', 'active', '加拿大10年期国债', '加拿大10年期国债', 'Canada 10-Year', 'bond', 'canada10year', '0.000', 'http://markets.wallstreetcn.com/bond/canada10year', 'http://www.investing.com/rates-bonds/canada-10-year-bond-yield', 'http://www.investing.com/rates-bonds/canada-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('97', 'Italy10Year', 'IT10Y-IT', 'active', '意大利10年期国债', '意大利10年期国债', 'Italy 10-Year', 'bond', 'italy10year', '0.000', 'http://markets.wallstreetcn.com/bond/italy10year', 'http://www.investing.com/rates-bonds/italy-10-year-bond-yield', 'http://www.investing.com/rates-bonds/italy-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('98', 'Russia10Year', '', 'active', '俄罗斯10年期国债', '俄罗斯10年期国债', 'Russia 10-Year', 'bond', 'russia10year', '0.000', 'http://markets.wallstreetcn.com/bond/russia10year', 'http://www.investing.com/rates-bonds/russia-10-year-bond-yield', 'http://www.investing.com/rates-bonds/russia-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('99', 'Austria10Year', 'AU10Y-AU', 'active', '奥地利10年期国债', '奥地利10年期国债', 'Austria 10-Year', 'bond', 'austria10year', '0.000', 'http://markets.wallstreetcn.com/bond/austria10year', 'http://www.investing.com/rates-bonds/austria-10-year-bond-yield', 'http://www.investing.com/rates-bonds/austria-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('100', 'China10Year', '', 'active', '中国10年期国债', '中国10年期国债', 'China 10-Year', 'bond', 'china10year', '0.000', 'http://markets.wallstreetcn.com/bond/china10year', 'http://www.investing.com/rates-bonds/china-10-year-bond-yield', 'http://www.investing.com/rates-bonds/china-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('101', 'Brazil10Year', 'BR10Y-BR', 'active', '巴西10年期国债', '巴西10年期国债', 'Brazil 10-Year', 'bond', 'brazil10year', '0.000', 'http://markets.wallstreetcn.com/bond/brazil10year', 'http://www.investing.com/rates-bonds/brazil-10-year-bond-yield', 'http://www.investing.com/rates-bonds/brazil-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('102', 'Argentina30Year', '', 'active', '阿根廷30年期国债', '阿根廷30年期国债', 'Argentina 30-Year', 'bond', 'argentina30year', '0.000', 'http://markets.wallstreetcn.com/bond/argentina30year', 'http://www.investing.com/rates-bonds/argentina-30-year-bond-yield', 'http://www.investing.com/rates-bonds/argentina-30-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('103', 'Mexico10Year', '', 'active', '墨西哥10年期国债', '墨西哥10年期国债', 'Mexico 10-Year', 'bond', 'mexico10year', '0.000', 'http://markets.wallstreetcn.com/bond/mexico10year', 'http://www.investing.com/rates-bonds/mexico-10-year', 'http://www.investing.com/rates-bonds/mexico-10-year', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('104', 'SouthKorea10Year', '', 'active', '韩国10年期国债', '韩国10年期国债', 'South Korea 10-Year', 'bond', 'southkorea10year', '0.000', 'http://markets.wallstreetcn.com/bond/southkorea10year', 'http://www.investing.com/rates-bonds/south-korea-10-year-bond-yield', 'http://www.investing.com/rates-bonds/south-korea-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('105', 'Indonesia10Year', '', 'active', '印尼10年期国债', '印尼10年期国债', 'Indonesia 10-Year', 'bond', 'indonesia10year', '0.000', 'http://markets.wallstreetcn.com/bond/indonesia10year', 'http://www.investing.com/rates-bonds/indonesia-10-year-bond-yield', 'http://www.investing.com/rates-bonds/indonesia-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('106', 'India10Year', '', 'active', '印度10年期国债', '印度10年期国债', 'India 10-Year', 'bond', 'india10year', '0.000', 'http://markets.wallstreetcn.com/bond/india10year', 'http://www.investing.com/rates-bonds/india-10-year-bond-yield', 'http://www.investing.com/rates-bonds/india-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('107', 'SaudiArabia1Year', '', 'active', '沙特1年期国债', '沙特1年期国债', 'Saudi Arabia 1-Year', 'bond', 'saudiarabia1year', '0.000', 'http://markets.wallstreetcn.com/bond/saudiarabia1year', 'http://www.investing.com/rates-bonds/saudi-arabia-1-year-bond-yield', 'http://www.investing.com/rates-bonds/saudi-arabia-1-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('108', 'SouthAfrica10Year', '', 'active', '南非10年期国债', '南非10年期国债', 'South Africa 10-Year', 'bond', 'southafrica10year', '0.000', 'http://markets.wallstreetcn.com/bond/southafrica10year', 'http://www.investing.com/rates-bonds/south-africa-10-year-bond-yield', 'http://www.investing.com/rates-bonds/south-africa-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('109', 'XAUAUDpro', '', 'active', '黄金/澳元', '黄金/澳元', 'XAU/AUD', 'commodity', 'xauaud', '0.00', 'http://markets.wallstreetcn.com/commodity/xauaud', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('110', 'XAUCHFpro', '', 'active', '黄金/瑞郎', '黄金/瑞郎', 'XAU/CHF', 'commodity', 'xauchf', '0.00', 'http://markets.wallstreetcn.com/commodity/xauchf', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('111', 'XAUEURpro', '', 'active', '黄金/欧元', '黄金/欧元', 'XAU/EUR', 'commodity', 'xaueur', '0.00', 'http://markets.wallstreetcn.com/commodity/xaueur', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('112', 'XAUGBPpro', '', 'active', '黄金/英镑', '黄金/英镑', 'XAU/GBP', 'commodity', 'xaugbp', '0.00', 'http://markets.wallstreetcn.com/commodity/xaugbp', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('113', 'XAUJPYpro', '', 'active', '黄金/日元', '黄金/日元', 'XAU/JPY', 'commodity', 'xaujpy', '0.00', 'http://markets.wallstreetcn.com/commodity/xaujpy', 'MT4', '', '', '', '', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('114', '000001', '', 'active', '上证指数', '上证指数', 'SSE Composite Index', 'indice', '000001', '0.00', 'http://markets.wallstreetcn.com/indice/000001', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://qt.gtimg.cn/q=sh000001', '每周一到周五上午时段9:30-11:30，下午时段13:00-15:00。周六、周日和上海证券交易所、深圳证券交易所公告的休市日不交易', 'china.py', '0.01', '5', '', '3157.7', '3157.7', '1423642644', '1423638196', '0');
INSERT INTO `ax_config` VALUES ('115', '399006', '', 'active', '创业板指数', '创业板指数', 'Growth Enterprise Index', 'indice', '399006', '0.00', 'http://markets.wallstreetcn.com/indice/399006', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://qt.gtimg.cn/q=sz399006', '每周一到周五上午时段9:30-11:30，下午时段13:00-15:00。周六、周日和上海证券交易所、深圳证券交易所公告的休市日不交易', 'china.py', '0.01', '5', '', '1772.84', '1772.84', '1423642646', '1423638356', '0');
INSERT INTO `ax_config` VALUES ('116', '399300', '', 'active', '沪深300', '沪深300指数', 'CSI 300 Index', 'indice', '399300', '0.00', 'http://markets.wallstreetcn.com/indice/399300', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://qt.gtimg.cn/q=sz399300', '每周一到周五上午时段9:30-11:30，下午时段13:00-15:00。周六、周日和上海证券交易所、深圳证券交易所公告的休市日不交易', 'china.py', '0.01', '5', '', '3434.12', '3434.12', '1423642646', '1423638356', '0');
INSERT INTO `ax_config` VALUES ('117', '399001', '', 'active', '深证成指', '深证成指', 'Shenzhen Component Index', 'indice', '399001', '0.00', 'http://markets.wallstreetcn.com/indice/399001', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://api.money.netease.com/data/feed/0000001,1399006,1399300,1399001,money.api?callback=mycallback', 'http://qt.gtimg.cn/q=sz399001', '每周一到周五上午时段9:30-11:30，下午时段13:00-15:00。周六、周日和上海证券交易所、深圳证券交易所公告的休市日不交易', 'china.py', '0.01', '5', '', '11265.6', '11265.6', '1423642647', '1423638356', '0');
INSERT INTO `ax_config` VALUES ('118', 'US10Year', 'US10Y', 'active', '美国10年期国债 ', '美债利率', 'U.S. 10-Year', 'bond', 'us10year', '0.000', 'http://markets.wallstreetcn.com/bond/us10year', 'http://www.investing.com/rates-bonds/u.s.-10-year-bond-yield', 'http://www.investing.com/rates-bonds/u.s.-10-year-bond-yield', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=US10Y&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', '', 'investing_bond.py', '0.01', '5', '', '1.9774', '1.977', '1423642648', '1423642479', '0');
INSERT INTO `ax_config` VALUES ('119', 'HKG33INDEX', '.HSI', 'active', '恒生指数', '恒生指数', 'Hang Seng', 'indice', 'hkg33index', '0.00', 'http://markets.wallstreetcn.com/indice/hkg33index', 'http://www.investing.com/indices/hang-sen-40?cid=38011', 'http://quote.eastmoney.com/hk/zs110000.html', 'http://qt.gtimg.cn/q=hkHSI', '北京时间9:30-12:00 13:30-16:00', 'investing_index.py', '0.01', '5', 'investing与网易是延迟15分钟，腾讯财经是实时的', '24315', '24321.3', '1423642650', '1423641600', '0');
INSERT INTO `ax_config` VALUES ('121', 'SPX500INDEX', '.SPX', 'active', '标普500', '标普500', 'S&P 500', 'indice', 'spx500index', '0.00', 'http://markets.wallstreetcn.com/indice/spx500index', 'http://www.investing.com/indices/us-spx-500?cid=40826', 'http://quote.eastmoney.com/gb/zsSPX.html', 'http://qt.gtimg.cn/q=usINX', '', 'investing_index.py', '0.01', '5', '', '2068.59', '2068.59', '1423642650', '1423603740', '0');
INSERT INTO `ax_config` VALUES ('123', 'NAS100INDEX', '.NDX', 'active', '纳斯达克100', '纳斯达克100', 'Nasdaq 100', 'indice', 'nas100index', '0.00', 'http://markets.wallstreetcn.com/indice/nas100index', 'http://www.investing.com/indices/nq-100?cid=23660', 'http://finance.yahoo.com/q?s=^NDX', '', '北京时间夏令时间(9:30pm-3:30am)　冬令时间(10:30pm-4:30am)', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('125', 'US30INDEX', '.DJI', 'active', '道琼斯', '道琼斯', 'Dow 30', 'indice', 'us30index', '0.00', 'http://markets.wallstreetcn.com/indice/us30index', 'http://www.investing.com/indices/us-30?cid=23656', 'http://quote.eastmoney.com/gb/zsINDU.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('127', 'JPN225INDEX', '.N225', 'active', '日经指数', '日经指数', 'Nikkei 225', 'indice', 'jpn225index', '0.00', 'http://markets.wallstreetcn.com/indice/jpn225index', 'http://www.investing.com/indices/japan-ni225', 'http://quote.eastmoney.com/gb/zsNKY.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('129', 'EUSTX50INDEX', '', 'active', '欧洲Stoxx50', '欧洲Stoxx50', 'DJ Euro Stoxx 50', 'indice', 'eustx50index', '0.00', 'http://markets.wallstreetcn.com/indice/eustx50index', 'http://www.investing.com/indices/eu-stoxx50?cid=40828', 'http://www.investing.com/indices/eu-stoxx50?cid=40828', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('131', 'GER30INDEX', '.GDAXI', 'active', '德国DAX', '德国DAX', 'DAX', 'indice', 'ger30index', '0.00', 'http://markets.wallstreetcn.com/indice/ger30index', 'http://www.investing.com/indices/germany-30?cid=23657', 'http://quote.eastmoney.com/gb/zsDAX.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('133', 'UK100INDEX', '.FTSE', 'active', '英国富时', '英国富时', 'FTSE 100', 'indice', 'uk100index', '0.00', 'http://markets.wallstreetcn.com/indice/uk100index', 'http://www.investing.com/indices/uk-100?cid=27517', 'http://quote.eastmoney.com/gb/zsUKX.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('135', 'FRA40INDEX', '.FCHI', 'active', '法国CAC', '法国CAC', 'CAC 40', 'indice', 'fra40index', '0.00', 'http://markets.wallstreetcn.com/indice/fra40index', 'http://www.investing.com/indices/france-40?cid=23658', 'http://quote.eastmoney.com/gb/zsCAC.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('137', 'ITA40INDEX', '.FTMIB', 'active', '意大利FTSE MIB', '意大利FTSE MIB', 'FTSE MIB', 'indice', 'ita40index', '0.00', 'http://markets.wallstreetcn.com/indice/ita40index', 'http://www.investing.com/indices/it-mib-40?cid=27309', 'http://quote.eastmoney.com/gb/zsFTSEMIB.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('139', 'ESP35INDEX', '.IBEX', 'active', '西班牙IBEX 35', '西班牙IBEX 35', 'IBEX 35', 'indice', 'esp35index', '0.00', 'http://markets.wallstreetcn.com/indice/esp35index', 'http://www.investing.com/indices/spain-35?cid=26491', 'http://quote.eastmoney.com/gb/zsIBEX.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('141', 'AUS200INDEX', '.AXJO', 'active', '澳大利亚ASX 200', '澳大利亚ASX 200', 'S&P/ASX 200', 'indice', 'aus200index', '0.00', 'http://markets.wallstreetcn.com/indice/aus200index', 'http://www.investing.com/indices/aus-200', 'http://finance.yahoo.com/q?s=^AXJO', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('143', 'Portugal10Year', '', 'active', '葡萄牙10年期国债', '葡萄牙10年期国债', 'Portugal 10-Year', 'bond', 'portugal10year', '0.000', 'http://markets.wallstreetcn.com/bond/portugal10year', 'http://www.investing.com/rates-bonds/portugal-10-year-bond-yield', 'http://www.investing.com/rates-bonds/portugal-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('145', 'Ireland10Year', '', 'active', '爱尔兰10年期国债', '爱尔兰10年期国债', 'Ireland 10-Year', 'bond', 'ireland10year', '0.00', 'http://markets.wallstreetcn.com/bond/ireland10year', 'http://www.investing.com/rates-bonds/ireland-10-year-bond-yield', 'http://www.investing.com/rates-bonds/ireland-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('147', 'Greece10Year', '', 'active', '希腊10年期国债', '希腊10年期国债', 'Greece 10-Year', 'bond', 'greece10year', '0.000', 'http://markets.wallstreetcn.com/bond/greece10year', 'http://www.investing.com/rates-bonds/greece-10-year-bond-yield', 'http://www.investing.com/rates-bonds/greece-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('149', 'Spain10Year', '', 'active', '西班牙10年期国债', '西班牙10年期国债', 'Spain 10-Year', 'bond', 'spain10year', '0.000', 'http://markets.wallstreetcn.com/bond/spain10year', 'http://www.investing.com/rates-bonds/spain-10-year-bond-yield', 'http://www.investing.com/rates-bonds/spain-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('151', 'AthensGeneralINDEX', '', 'active', '希腊综合股指', '希腊综合股指', 'Athens General-Composite', 'indice', 'athensgeneralindex', '0.00', 'http://markets.wallstreetcn.com/indice/athensgeneralindex', 'http://www.investing.com/indices/athens-general', 'http://quote.eastmoney.com/gb/zsASE.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('153', 'BSESensex30INDEX', '', 'active', '印度孟买SENSEX指数', '印度孟买SENSEX指数', 'BSE Sensex 30', 'indice', 'bsesensex30index', '0.00', 'http://markets.wallstreetcn.com/indice/bsesensex30index', 'http://www.investing.com/indices/sensex', 'http://quote.eastmoney.com/gb/zsSENSEX.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('155', 'FTSEJSEAllShareINDEX', '', 'active', '南非综合指数', '南非综合指数', 'FTSE/JSE All Share', 'indice', 'ftsejseallshareindex', '0.00', 'http://markets.wallstreetcn.com/indice/ftsejseallshareindex', 'http://www.investing.com/indices/ftse-jse-all-share', 'http://www.investing.com/indices/ftse-jse-all-share', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('157', 'BovespaINDEX', '.BVSP-BR', 'active', '巴西BOVESPA股票指数', '巴西BOVESPA股票指数', 'Bovespa', 'indice', 'bovespaindex', '0.00', 'http://markets.wallstreetcn.com/indice/bovespaindex', 'http://www.investing.com/indices/bovespa', 'http://quote.eastmoney.com/gb/zsIBOV.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('159', 'IPCINDEX', '', 'active', '墨西哥BOLSA指数', '墨西哥BOLSA指数', 'IPC', 'indice', 'ipcindex', '0.00', 'http://markets.wallstreetcn.com/indice/ipcindex', 'http://www.investing.com/indices/ipc', 'http://quote.eastmoney.com/gb/zsMEXBOL.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('161', 'MICEXINDEX', '', 'active', '俄罗斯MICEX指数', '俄罗斯MICEX指数', 'MICEX', 'indice', 'micexindex', '0.00', 'http://markets.wallstreetcn.com/indice/micexindex', 'http://www.investing.com/indices/mcx', 'http://www.investing.com/indices/mcx', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('163', 'SPTSXCompositeINDEX', '', 'active', '加拿大S&P/TSX综合指数', '加拿大S&P/TSX综合指数', 'S&P/TSX Composite', 'indice', 'sptsxcompositeindex', '0.00', 'http://markets.wallstreetcn.com/indice/sptsxcompositeindex', 'http://www.investing.com/indices/s-p-tsx-composite', 'http://quote.eastmoney.com/gb/zsSPTSX.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('165', 'JakartaStockExchangeCompositeINDEX', '.JKSE', 'active', '印尼雅加达综合指数', '印尼雅加达综合指数', 'Jakarta Stock Exchange Composite', 'indice', 'jakartastockexchange', '0.00', 'http://markets.wallstreetcn.com/indice/jakartastockexchange', 'http://www.investing.com/indices/idx-composite', 'http://quote.eastmoney.com/gb/zsJCI.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('167', 'PSEiCompositeINDEX', '.PSI', 'active', '菲律宾PSE综合股价指数', '菲律宾PSE综合股价指数', 'PSEi Composite', 'indice', 'pseicompositeindex', '0.00', 'http://markets.wallstreetcn.com/indice/pseicompositeindex', 'http://www.investing.com/indices/psei-composite', 'http://www.investing.com/indices/psei-composite', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('169', 'ThailandSETINDEX', '.SETI', 'active', '泰国SET指数', '泰国SET指数', 'Thailand SET', 'indice', 'thailandsetindex', '0.00', 'http://markets.wallstreetcn.com/indice/thailandsetindex', 'http://www.investing.com/indices/thailand-set', 'http://www.investing.com/indices/thailand-set', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('171', 'FTSEMalaysiaKLCIINDEX', '.KLSE', 'active', '富时马来西亚KLCI综合指数', '富时马来西亚KLCI综合指数', 'FTSE Malaysia KLCI', 'indice', 'ftsemalaysiaklciinde', '0.00', 'http://markets.wallstreetcn.com/indice/ftsemalaysiaklciinde', 'http://www.investing.com/indices/ftse-malaysia-klci', 'http://quote.eastmoney.com/gb/zsFBMKLC.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('173', 'KOSPIINDEX', '.KS11', 'active', '韩国成份指数', '韩国成份指数', 'KOSPI', 'indice', 'kospiindex', '0.00', 'http://markets.wallstreetcn.com/indice/kospiindex', 'http://www.investing.com/indices/kospi', 'http://quote.eastmoney.com/gb/zsKOSPI.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('175', 'SingaporeStraitsTimeINDEX', '.FTSTI', 'active', '富时新加坡海峡时报指数', '富时新加坡海峡时报指数', 'Singapore Straits Time', 'indice', 'singaporestraitstime', '0.00', 'http://markets.wallstreetcn.com/indice/singaporestraitstime', 'http://www.investing.com/indices/singapore-straits-time', 'http://quote.eastmoney.com/gb/zsFSSTI.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('177', 'TadawulAllShareINDEX', '', 'active', '沙特阿拉伯综合指数', '沙特阿拉伯综合指数', 'Tadawul All Share', 'indice', 'tadawulallshareindex', '0.00', 'http://markets.wallstreetcn.com/indice/tadawulallshareindex', 'http://www.investing.com/indices/tasi', 'http://www.investing.com/indices/tasi', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('179', 'BTCUSD', 'BTC=', 'active', '比特币兑美元', '比特币兑美元', 'BTC/USD', 'forex', 'btcusd', '0.00', 'http://markets.wallstreetcn.com/forex/btcusd', 'http://www.investing.com/currencies/btc-usd', 'http://www.investing.com/currencies/btc-usd', '', '24小时', 'investing_forex.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('181', 'Australia10Year', '', 'inactive', '澳大利亚10年期国债', null, 'Australia 10-Year', 'bond', 'australia10year', '0.00', 'http://markets.wallstreetcn.com/bond/australia10year', 'http://www.investing.com/rates-bonds/australia-10-year-bond-yield', 'http://www.investing.com/rates-bonds/australia-10-year-bond-yield', '', '', 'investing_bond.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('183', 'USDCNY', '', 'active', '美元/人民币', '美元/人民币', 'USD/CNY', 'forex', 'usdcny', '0.0000', 'http://markets.wallstreetcn.com/forex/usdcny', 'http://www.investing.com/currencies/usd-cny', 'http://www.investing.com/currencies/usd-cny', 'http://quote.cnbc.com/quote-html-webservice/quote.htm?symbols=CNY%3D&symbolType=symbol&requestMethod=quick&exthrs=1&extMode=&fund=1&entitlement=0&skipcache=&extendedMask=1&partnerId=2&output=json&noform=1', '24小时', 'investing_open_close.py', '0.001', '5', '', '6.2417', '6.2423', '1423642651', '1423642626', '0');
INSERT INTO `ax_config` VALUES ('185', 'AUTD', '', 'active', '上海黄金t+d', null, '上海黄金autd', 'commodity', 'autd', '0.00', 'http://markets.wallstreetcn.com/commodity/autd', 'http://jry.baidao.com/api/hq/npdata.do?ids=101', 'http://jry.baidao.com/api/hq/npdata.do?ids=101', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('187', 'NASINDEX', '', 'active', '纳斯达克', '纳斯达克', 'Nasdaq', 'indice', 'nasindex', '0.00', 'http://markets.wallstreetcn.com/indice/nasindex', 'http://www.investing.com/indices/nasdaq-composite', 'http://quote.eastmoney.com/gb/zsCCMP.html', '', '', 'investing_index.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('189', 'AGTD', '', 'active', '上海白银t+d', null, '上海白银ag(t+d)', 'commodity', 'agtd', '0.00', 'http://markets.wallstreetcn.com/commodity/agtd', 'http://jry.baidao.com/api/hq/npdata.do?ids=102', 'http://jry.baidao.com/api/hq/npdata.do?ids=102', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('191', 'AU9999', '', 'active', '上海黄金9999', null, '上海黄金99.99', 'commodity', 'au9999', '0.00', 'http://markets.wallstreetcn.com/commodity/au9999', 'http://jry.baidao.com/api/hq/npdata.do?ids=103', 'http://jry.baidao.com/api/hq/npdata.do?ids=103', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('193', 'AU9995', '', 'active', '上海黄金9995', null, '上海黄金99.95', 'commodity', 'au9995', '0.00', 'http://markets.wallstreetcn.com/commodity/au9995', 'http://jry.baidao.com/api/hq/npdata.do?ids=104', 'http://jry.baidao.com/api/hq/npdata.do?ids=104', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('195', 'AU100G', '', 'active', '上海100克金条', null, '上海100克金条', 'commodity', 'au100g', '0.00', 'http://markets.wallstreetcn.com/commodity/au100g', 'http://jry.baidao.com/api/hq/npdata.do?ids=105', 'http://jry.baidao.com/api/hq/npdata.do?ids=105', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('197', 'AU50G', '', 'inactive', '上海50克金条', null, '上海50克金条', 'commodity', 'au50g', '0.00', 'http://markets.wallstreetcn.com/commodity/au50g', 'http://jry.baidao.com/api/hq/npdata.do?ids=106', 'http://jry.baidao.com/api/hq/npdata.do?ids=106', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('199', 'AuTN1', '', 'inactive', '上海黄金单月延期', null, '上海黄金单月延期', 'commodity', 'autn1', '0.00', 'http://markets.wallstreetcn.com/commodity/autn1', 'http://jry.baidao.com/api/hq/npdata.do?ids=107', 'http://jry.baidao.com/api/hq/npdata.do?ids=107', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('201', 'AuTN2', '', 'inactive', '上海黄金双月延期', null, '上海黄金双月延期', 'commodity', 'autn2', '0.00', 'http://markets.wallstreetcn.com/commodity/autn2', 'http://jry.baidao.com/api/hq/npdata.do?ids=108', 'http://jry.baidao.com/api/hq/npdata.do?ids=108', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('203', 'AG9999', '', 'inactive', '上海白银9999', null, '上海白银9999', 'commodity', 'ag9999', '0.00', 'http://markets.wallstreetcn.com/commodity/ag9999', 'http://jry.baidao.com/api/hq/npdata.do?ids=109', 'http://jry.baidao.com/api/hq/npdata.do?ids=109', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('205', 'AG999', '', 'inactive', '上海白银999', null, '上海白银999', 'commodity', 'ag999', '0.00', 'http://markets.wallstreetcn.com/commodity/ag999', 'http://jry.baidao.com/api/hq/npdata.do?ids=110', 'http://jry.baidao.com/api/hq/npdata.do?ids=110', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('207', 'PT9995', '', 'active', '上海铂金9995', null, '上海铂金9995', 'commodity', 'pt9995', '0.00', 'http://markets.wallstreetcn.com/commodity/pt9995', 'http://jry.baidao.com/api/hq/npdata.do?ids=111', 'http://jry.baidao.com/api/hq/npdata.do?ids=111', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('209', 'MAUTD', '', 'active', '上海迷你黄金t+d', null, '上海迷你黄金mAu(t+d) 迷你黄金延期', 'commodity', 'mautd', '0.00', 'http://markets.wallstreetcn.com/commodity/mautd', 'http://jry.baidao.com/api/hq/npdata.do?ids=112', 'http://jry.baidao.com/api/hq/npdata.do?ids=112', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('211', 'TTYXAGUSD', '', 'active', '天津现货白银', null, '天津现货白银', 'commodity', 'ttyxagusd', '0.00', 'http://markets.wallstreetcn.com/commodity/ttyxagusd', 'http://jry.baidao.com/api/hq/npdata.do?ids=1', 'http://jry.baidao.com/api/hq/npdata.do?ids=1', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('213', 'TTJPD', '', 'active', '天津现货钯金', null, '天津现货钯金', 'commodity', 'ttjpd', '0.00', 'http://markets.wallstreetcn.com/commodity/ttjpd', 'http://jry.baidao.com/api/hq/npdata.do?ids=5', 'http://jry.baidao.com/api/hq/npdata.do?ids=5', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('215', 'TTJPT', '', 'active', '天津现货铂金', null, '天津现货铂金', 'commodity', 'ttjpt', '0.00', 'http://markets.wallstreetcn.com/commodity/ttjpt', 'http://jry.baidao.com/api/hq/npdata.do?ids=6', 'http://jry.baidao.com/api/hq/npdata.do?ids=6', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('217', 'TTNI', '', 'active', '天津现货镍', null, '天津现货镍', 'commodity', 'ttni', '0.00', 'http://markets.wallstreetcn.com/commodity/ttni', 'http://jry.baidao.com/api/hq/npdata.do?ids=7', 'http://jry.baidao.com/api/hq/npdata.do?ids=7', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('219', 'GZAG100G', '', 'inactive', '广州现货白银100G', null, '广州现货白银100G', 'commodity', 'gzag100g', '0.00', 'http://markets.wallstreetcn.com/commodity/gzag100g', 'http://www.pmec.com/flash/data/230_AG100.xml', 'http://www.pmec.com/flash/data/230_AG100.xml', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('221', 'GZAG9999', '', 'inactive', '广州现货白银9999', null, '广州现货白银9999', 'commodity', 'gzag9999', '0.00', 'http://markets.wallstreetcn.com/commodity/gzag9999', 'http://www.pmec.com/flash/data/230_AG1.xml', 'http://www.pmec.com/flash/data/230_AG1.xml', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('223', 'GZAG9995', '', 'inactive', '广州现货白银9995', null, '广州现货白银9995', 'commodity', 'gzag9995', '0.00', 'http://markets.wallstreetcn.com/commodity/gzag9995', 'http://www.pmec.com/flash/data/230_AG15.xml', 'http://www.pmec.com/flash/data/230_AG15.xml', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('225', 'GZPD', '', 'inactive', '广州现货钯金', null, '广州现货钯金', 'commodity', 'gzpd', '0.00', 'http://markets.wallstreetcn.com/commodity/gzpd', 'http://www.pmec.com/flash/data/100_PDXA.xml', 'http://www.pmec.com/flash/data/100_PDXA.xml', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('227', 'GZPT', '', 'inactive', '广州现货铂金', null, '广州现货铂金', 'commodity', 'gzpt', '0.00', 'http://markets.wallstreetcn.com/commodity/gzpt', 'http://www.pmec.com/flash/data/100_PTXA.xml', 'http://www.pmec.com/flash/data/100_PTXA.xml', '', '', 'chinayintianxia.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('229', 'GOLDETF', '', 'inactive', '黄金ETF', null, '黄金ETF', 'commodity', 'goldetf', '0.00', 'http://www.goldtoutiao.com/market', 'http://fx.caiku.com/pair/etf_chart/SPT_GLD?page=', 'http://fx.caiku.com/pair/etf_chart/SPT_GLD?page=', '', '', 'etf_caiku.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('231', 'SILVERETF', '', 'inactive', '白银ETF', null, '白银ETF', 'commodity', 'silveretf', '0.00', 'http://www.goldtoutiao.com/market', 'http://fx.caiku.com/pair/etf_chart/SPT_SVR?page=', 'http://fx.caiku.com/pair/etf_chart/SPT_SVR?page=', '', '', 'etf_caiku.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('233', 'GOLDCFTC', '', 'inactive', '黄金CFTC', null, '黄金CFTC', 'commodity', 'goldcftc', '0.00', 'http://www.goldtoutiao.com/market', 'http://fx.caiku.com/pair/cftc_chart/SPT_GLD?page=', 'http://fx.caiku.com/pair/cftc_chart/SPT_GLD?page=', '', '', 'CFTC.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('235', 'SILVERCFTC', '', 'inactive', '白银CFTC', null, '白银CFTC', 'commodity', 'silvercftc', '0.00', 'http://www.goldtoutiao.com/market', 'http://fx.caiku.com/pair/cftc_chart/SPT_GLD?page=', 'http://fx.caiku.com/pair/cftc_chart/SPT_GLD?page=', '', '', 'CFTC.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('237', 'GOLDFIXPRICE', '', 'inactive', '黄金伦敦定盘价', null, '黄金伦敦定盘价', 'commodity', 'goldfixprice', '0.00', 'http://www.goldtoutiao.com/market', 'http://quote.24k99.com/gold-fixing.aspx', 'http://quote.24k99.com/gold-fixing.aspx', '', '', 'fix_price.py', '0', '0', '', '0', '0', '0', '0', '0');
INSERT INTO `ax_config` VALUES ('239', 'SILVERFIXPRICE', '', 'inactive', '白银伦敦定盘价', null, '白银伦敦定盘价', 'commodity', 'silverfixprice', '0.00', 'http://www.goldtoutiao.com/market', 'http://quote.24k99.com/gold-fixing.aspx', 'http://quote.24k99.com/gold-fixing.aspx', '', '', 'fix_price.py', '0', '0', '', '0', '0', '0', '0', '0');

-- ----------------------------
-- Table structure for `ax_monitor_log`
-- ----------------------------
DROP TABLE IF EXISTS `ax_monitor_log`;
CREATE TABLE `ax_monitor_log` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `symbol` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `ctime` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '对比时间',
  `record` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `source` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '来源',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of ax_monitor_log
-- ----------------------------
